# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 891e92a006f787a9c957d3e1682a73e542e460cd2cbfec91ca93b56c1a6bb571865b57e8e476400254abbb39485e94ed461a821047a84f361d0098fa76d5b59e

test:
  secret_key_base: f2c51c68d7993a0efb03e275922e648a37691e29a624c7f2a9baa1b56db92173a2ad42520949d476cafa5759daa6c0df513c79ccf8d940550fdf44be4338569a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
